server:
  port: 8081

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/food_db?useSSL=false&allowPublicKeyRetrieval=true
    username: myfood
    password: myfood

mybatis:
  mapper-locations: mybatis/mapper/*.xml
  type-aliases-package: com.practice.homework
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    root: info